# Generated by Django 2.2.14 on 2020-11-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201117_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='tex-product'),
            preserve_default=False,
        ),
    ]
