# Generated by Django 2.2.14 on 2020-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
