# Generated by Django 2.2.14 on 2020-12-09 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0023_auto_20201209_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='shipping_address',
        ),
    ]
